### PR TITLE
cross-platform timeout

### PR DESCRIPTION
**Pull request by anderson-dan-w**
Adapted from [StackOverflow](https://stackoverflow.com/a/10012262/2272638)

confirmed that toy functions (`sleep $n`) return either `0` (success) or `-9` (pkill) on timeout.

Does our testing framework include MacOS (which was the motivating use-case for this change)? Or Windows?

### CODE REVIEW

**Comment by alexandraj777** [comment]
Looks like we're still on Travis for this repo, does Circle CI support MacOS?

**Comment by pfhayes** [comment]
it appears that they do! https://circleci.com/open-source/

**Comment by alexandraj777** [comment]
Awesome! Sounds like another point in favor of moving this repo over

**Comment by anderson-dan-w** [comment]
I was gonna say it might be simple to just add `os: -linux; -osx` to the `.travis.yml` but apparently travis doesn't support python on MacOS....

**Comment by alexandraj777** [comment]
@anderson-dan-w yeah travis support for Mac hasn't worked for us, that's why we haven't used it previously

**Comment by anderson-dan-w** [comment]
update - it doesnt really work as hoped on circleci either - you cant use any of the docker images with macOS

**Comment by anderson-dan-w** [comment]
Ohh, even with a mac test, this code path isn't tested. I'll see if it's easy enough to add in, but otherwise might punt on that and just test something locally? Not ideal but don't want too much of a rabbit hole

**Comment by alexandraj777** [comment]
Sounds like overhauling testing too much is out of scope for this PR. If you've tested this change locally on your mac I'm comfortable with you merging it in. You can make the call of how deep you'd recommend going for testing, and whether or not that's a followon to this task, or something we'll handle later

**Comment by anderson-dan-w** [comment]
Testing this, even just locally, was ... not easy or clear, but I eventually was able to confirm that the new timer code successfully kills jobs and returns non-zero exit status.

**Pull request merged**
